Unittesting implementation
nicolbidone/Clean_Marvel_Kotlin pull request #6
Opened 2019-04-09 16:15 UTC by nicolbidone

![image](https://user-images.githubusercontent.com/48327006/55816787-82268680-5ac9-11e9-8e26-c1d1173ca74d.png)

2019-04-09 17:18 UTC, SartiMau requested changes

2019-04-09 17:18 UTC, SartiMau commented on app/src/main/java/com/puzzlebench/clean_marvel_kotlin/presentation/MainActivity.kt
> +            realmDestroy()
why do you destroy de DB??

2019-04-09 17:18 UTC, SartiMau commented on app/src/test/java/com/puzzlebench/clean_marvel_kotlin/domain/usecase/SetCharacterStoredUseCaseTest.kt
> +        `when`(characterStored.setCharacters(itemsCharacters)).then {}
why do you have the "{}" ?

2019-04-09 17:18 UTC, SartiMau commented on app/src/test/java/com/puzzlebench/clean_marvel_kotlin/fragment/mvp/FragmentModelTest.kt
> +        getSingleCharacterServiceUseCase = GetSingleCharacterServiceUseCase(characterService, ZERO_VALUE)
this must be a mock

2019-04-09 17:18 UTC, SartiMau commented on app/src/test/java/com/puzzlebench/clean_marvel_kotlin/fragment/mvp/FragmentModelTest.kt
> +        val itemsCharacters = CharactersFactory.getMockCharacter()
you have to mock a character here

2019-04-09 17:18 UTC, SartiMau commented on app/src/test/java/com/puzzlebench/clean_marvel_kotlin/fragment/mvp/FragmentPresenterTest.kt
> +    private lateinit var getSingleCharacterServiceUseCase: GetSingleCharacterServiceUseCase
this must be a mock

2019-04-09 17:18 UTC, SartiMau commented on app/src/test/java/com/puzzlebench/clean_marvel_kotlin/fragment/mvp/FragmentPresenterTest.kt
> +        getSingleCharacterServiceUseCase = GetSingleCharacterServiceUseCase(characterService, ZERO_VALUE)
this must be a mock

2019-04-09 17:18 UTC, SartiMau commented on app/src/test/java/com/puzzlebench/clean_marvel_kotlin/presentation/mvp/CharacterModelTests.kt
> +
the UseCases must be mocks

2019-04-09 17:18 UTC, SartiMau commented on app/src/test/java/com/puzzlebench/clean_marvel_kotlin/presentation/mvp/CharacterModelTests.kt
> +    }
You forget the verify here.

2019-04-09 17:18 UTC, SartiMau commented on app/src/test/java/com/puzzlebench/clean_marvel_kotlin/presentation/mvp/CharacterModelTests.kt
> +        Mockito.`when`(getCharacterStoredUseCase()).thenReturn(itemsCharacters)
You forget the verify here.

2019-04-09 17:18 UTC, SartiMau commented on app/src/test/java/com/puzzlebench/clean_marvel_kotlin/presentation/mvp/CharacterModelTests.kt
> +        Mockito.`when`(setCharacterStoredUseCase(itemsCharacters)).then { }
You forget the verify here.

2019-04-09 17:18 UTC, SartiMau commented on app/src/test/java/com/puzzlebench/clean_marvel_kotlin/presentation/mvp/CharacterPresenterTest.kt
> +    private lateinit var setCharacterStoredUseCase: SetCharacterStoredUseCase
the UseCases must be mocks

2019-04-09 18:57 UTC, nicolbidone commented on app/src/test/java/com/puzzlebench/clean_marvel_kotlin/fragment/mvp/FragmentModelTest.kt
> +        getSingleCharacterServiceUseCase = GetSingleCharacterServiceUseCase(characterService, ZERO_VALUE)
Done

2019-04-09 18:57 UTC, nicolbidone commented on app/src/test/java/com/puzzlebench/clean_marvel_kotlin/fragment/mvp/FragmentModelTest.kt
> +        val itemsCharacters = CharactersFactory.getMockCharacter()
Done

2019-04-09 18:57 UTC, nicolbidone commented on app/src/test/java/com/puzzlebench/clean_marvel_kotlin/fragment/mvp/FragmentPresenterTest.kt
> +    private lateinit var getSingleCharacterServiceUseCase: GetSingleCharacterServiceUseCase
Done

2019-04-09 18:57 UTC, nicolbidone commented on app/src/test/java/com/puzzlebench/clean_marvel_kotlin/presentation/mvp/CharacterModelTests.kt
> +
Done

2019-04-09 18:57 UTC, nicolbidone commented on app/src/test/java/com/puzzlebench/clean_marvel_kotlin/presentation/mvp/CharacterModelTests.kt
> +    }
Done

2019-04-09 18:58 UTC, nicolbidone commented on app/src/test/java/com/puzzlebench/clean_marvel_kotlin/presentation/mvp/CharacterModelTests.kt
> +        Mockito.`when`(getCharacterStoredUseCase()).thenReturn(itemsCharacters)
Done

2019-04-09 18:58 UTC, nicolbidone commented on app/src/test/java/com/puzzlebench/clean_marvel_kotlin/presentation/mvp/CharacterModelTests.kt
> +        Mockito.`when`(setCharacterStoredUseCase(itemsCharacters)).then { }
Done

2019-04-09 18:58 UTC, nicolbidone commented on app/src/test/java/com/puzzlebench/clean_marvel_kotlin/presentation/mvp/CharacterPresenterTest.kt
> +    private lateinit var setCharacterStoredUseCase: SetCharacterStoredUseCase
Done

2019-04-09 19:18 UTC, nicolbidone commented on app/src/test/java/com/puzzlebench/clean_marvel_kotlin/domain/usecase/SetCharacterStoredUseCaseTest.kt
> +        `when`(characterStored.setCharacters(itemsCharacters)).then {}
Done

2019-04-09 19:50 UTC, nicolbidone commented on app/src/main/java/com/puzzlebench/clean_marvel_kotlin/presentation/MainActivity.kt
> +            realmDestroy()
Done

2019-04-10 18:48 UTC, SartiMau approved these changes

2019-04-10 19:06 UTC, lucianoeli approved these changes

2019-04-10 19:10 UTC, merged